### ISSUE TITLE
Source files ?

### ISSUE THREAD

**Issue by lipsumar** [pimbrouwers/YUI-Pure-CSS-Extensions#1]
This is something i'd like to use, but as we use different grids (across many websites) we can not use this without the source (i suppose you generated this using something like https://github.com/yahoo/grunt-pure-grids or SCAA/LESS).

Can you add the source file(s) to this repo ? Or is there another repo with the sources ?

**Comment by pimbrouwers** [comment]
Hi there,

Not entirely sure what you're asking for. This is designed to be an extension of the PureCss library from YUI (purecss.io). The "src" file is the css file contained in the repository. It's meant to be dropped into a PureCSS project.

**Comment by lipsumar** [comment]
Then i suppose you generated the CSS file using a search/replace or something like that.

A PureCSS project does not need to be using grids of 5 and 24 (that's the default). If you want to generate yourself the CSS for a grid of units of 5, 7 and 12, you can use https://github.com/yahoo/grunt-pure-grids.

The CSS you have here is only good for the default grid (5 and 24).

I was looking for the code that might generate this CSS dynamically, based on grid units (again, just like grunt-pure-grids).

**Comment by pimbrouwers** [comment]
This is designed to work with the default YUI Pure CSS grid.

**Comment by lipsumar** [comment]
Never mind. We made that generator as a grunt task. 

Emmanuel

**Comment by pimbrouwers** [comment]
Src has been added. Gulp generator coming.
