### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by jauhari** [pimbrouwers/YUI-Pure-CSS-Extensions#4]
I think this is what we really need. But the question is simple. How to use it? Any step by step to integrated with PURECSS.io?

Regards

Jauhari

**Comment by mpwashburn** [comment]
Hi there. I want to try this on a static site I'm putting together. I'm still a bit green in many areas of development. Can you explain how to implement your files into mine?

**Comment by pimbrouwers** [comment]
Hi @mpwashburn! Thanks for reaching out. Happy to help you out.

I would start by downloading the source (https://github.com/pimbrouwers/YUI-Pure-CSS-Extensions/archive/master.zip). 

Once you unarchive it, there will be a folder insider called `dist`. In there is a single file. I would copy that file into your project folder and reference it in the `<head></head>` of your document using the `<link rel="stylesheet" type="text/css" href=""></link>` tag. Note that you'll need to update the HREF to be the relative path to your copy of the css file.

Hopefully that helps.

**Comment by pimbrouwers** [comment]
@jauhari Documentation has been added to the readme. Thanks for reaching out!
